JlMGPIeAjcoMDQiTTBGRrdCQGxjLzHiuYVjtugsEDVHGgfrTVwVrlSpeyKxXyXjYBTnwYMHOXYtIzKO220 = "bRSHFTCTkPuUwLDhWPmUvXOBFJgqKtVdavelpPtzQfvsCgEBxqueGCFnWxkRSkxfJfzEzYrGDOzbvlN"
AaAAAaAAaaaAaAaaaAaaaaaAaAAAAAAAAAaaAAaAAaAaAaaAAAAAaaAAAAaAaAaaAaaaaAaAaaAAaaAaAAAAAaAaAaAaaaAAAaaaAaAaaAAaAAAAaaaaAAaAaAAaAAAAAAAaAaaAAaaaaAaAaaaAaAaaaaAaAaAAAaAAAaaaaaAaaAAAAAAaAAaaaaaaaaaAAaaAaAaaaaaaaAAAaAAaAAAAAA = "EtgwNBNMRfhplabjchNDRkdPieunrJcAvEbOUHZNhxKqNwPMXKPqfzlphPutOhtHzYHkUWVhFBAmdUC"
AaaAaAAAaAaAAAAaaaAAAAaAaaaaAaAaaAAaAaAaaAAaAaaaaaaaAaaaAaAAAAaAAAaaaAaaaAAAAaaAAaaaaaAAaAAaaAaaaAAaaaaAaAaaAaAaAaAAaAaaAaAAAaaaAaaaAAaaAAaAAaAaaaAAAAAAAaaAAaAAaaAAaAAaAaAaAAAaAaaAaAAaAaaaAAaAAaAaAAaaAaaaAAaAAAAAAaaA = 247
aaaaaAAAAaAAaaaaaaAAAaAAAAaAaaAaAaaaAAAaAaAAaaaAaaaAaAaAAaAaAaAAAaAAAAAAaaaaaaaAAAaAAAAaAAaAAaAaAaAAaaaaAaAAAaAAAaaaAaAAAaAaaAAAAaAaaaaAAaaaaaAaAAAaaAaAAAaAAaAaaaAaaaaAAaAAaAAAaAaAaAAAAAAaAAAAAaaAAAAAaaAaAaaAaAaAaA = "kKEYQmTMosevgEMyDQglHMciWMcdwWswWDhAwnOCCyuetEQbHEmJQilyqNOMupTWWOlLhRmwsepmuMg"
feobWqXCdENgCbgxjhIqpTWvvAKcdGuZtEhRhseyvuYCeAxvSBsdctPbbhzwOXGgtToJgUGCxegQvkc212 = 257
JRREXaqOHBQdjmyQTcgteJMqEJExNrQedOMzMAmddQeGZgEUkykhHXZfPchHKyASblgslSUTXcXvAwJ210 = 327
wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww = 332
AaAAaaaaAaaAaAaaaaaaaaAaAAAAaaAaaAaaAAaaaAAAAaaAaAaAaAaaAaAaaAAAAAAaaaAaAAAaaaAaAAAAAaAAAAAAAaaAaAAaAAaAAAAAAaaaAaAaaaaAAaAaaAAaAAAAaaAaAaAaaAAAaAAaAAaaaAAaAAaAaAAAAAaAaaAaaAaaaaAaAaAaaaAaaAAaAAaaAAAAaAAAAA = "eePJcMyNsEhnJehmfMJzJECQOofjNFvJiTlRApLsBcQvuOIUZrHkFBaTIAiuKPLQomfrPYkJEqXCfcB"
aAaAaAAaAAAAaaaAaaAAAAaaaaaAAaAaaaAAaaaAaaaAAaAAAaaaaaAAaaaaaaAaAaAaAaAaaAaAAaaaAaAaAAaaaAAAaaaaaAaaaaAaaaaaaAaaAaAAaaAAaAaaaAaAaaAaAaAAAaaaaAaaaAAaaAaaaAAaaAaaaAAaaaAaAAaaAAAaAAAAaaaAaAAaaAaaAaAaAaAaAaaA = "guWPdloMCCcboZyDnHUvMOLsCQNzHkWLfiimuzWLbDszDsPOqKJEqLDYurzoZQGhfPkoJnCZUSdXmJD"
IixoGNidyDVlKIMLqziUkKHAxkZgbMtzIvYNzZQZmzehDrAMQSfDeFDmSWXcIfbHlCZunkbPlRuVbqS202 = "cQLETfDBskrSxrFwqoMjnhhTDgagVltjlXhGxvmGScJdanRUWhQfHsKXBmfdyMSEbvDJaytxZGScMCW"
lllIIIlIIIIIlIlIIlIllIlIIlllIlIIlIIllIIIlIIllIIlIIIlIllIIIlIllIIlllIlIIIlIIlIIlllIlIIIlIIlIlIllIlIIIlllllIIIlIIlIIllIlllllIllllIIIllIlllIlIlllllIIIIIIIIllIIlIlIlIllIlIllIIIIllIIIIIIIIIllIlIllIIllIlIIl = 456
KkgTCFCHcRwgnzfoslnnIIhouwWwjjjNAJkPwJmySngSOMuTdYUlWEpckOsfEdZBTyqwQGBfZjwpeWc198 = "szgTqBEgaALyrFaqeFduJOSATHFklIYyjcCjNpnvaAhbdPIjYlmASaYKcDDnozEpNvfgjLWdapTIZbU"
YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY = 268
K1659600450415203194 = 217
e1659600450415122192 = "FleBwcntNDoUvFBTyXWxHizWVZcZUTxjXswGymVNPruzqbVBfABzwYeDKKOMvnEEkgEFxNzCdVFzFmZ"
ByqpkLApczAsyxrCdxiqOyaZEmUTAmWAHZhOFBPrceuZzUAUHfRqiUllRQYJAibIZYdsEUZRRrkBZgz190 = "tNxsHidlRZwbgdktJdmnBsDAwxquESIucdtbeAQHAdwjiVllqradjnNzazjAVewAaqMUTekDQFszuMn"
ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ = 218
i186 = 878
llIlIllllIIIIIIlIlIlllIIllIIllIIllIllIlIlIIIIllllIIIlllIIIIllIlllIIIIIllllIIIlIIIlllllIllIllIllIIlllllIIIllllIIlllIIlllIIlIlIllIllllIIlllIlIIIlIIIIlIIlIIlIIIlIlIlIIllIIIIIIlIIIIlIllIlI = 570
xfCNmZtyrvcACSbTplaaucAkEArooRtrQferyGSSVsVGQIRWMhLFmdHnkojJkOdgWSwYaoxFQOstJLV182 = 627
t1659600450414579180 = "ZpTDKtIlzJEjvDARCWbGVYVzJOyXYSUMRoqfJuIhKFQVZfGLFqoSChCXUzdSGifSlJbuUQiAaUvyvlE"
LbiKeppJLKMYksrqUXbeqGMwrrKhpfINMsqvNbEnjNutuChygEvswalpragAxWJRcjtteIinJqflyDc178 = 303
V176 = 223
t174 = "vipvdeYUxkUBoeCVetZRADeBCbtGNnMzgoRNCExhQgkXoDFIYxRhWibzHAHsxoyaYQCsVQLCkSNdMUC"
t16596004504142468172 = 189
ykIyALfoQaAfcsGgWNzLVbBodYFUePpXDStRGLlBJGMKecnWpXIqkktvKRMBtaAkfEQEaJpUAIcXxog170 = "EIUAnWdYOXJrzHQTDQTnzPQeRByhMaPogrTyjFbTRcBGAXpSGMZalnSHbXjPHnSchBJptYzViAadKdQ"
f1659600450414079168 = "rfGjVRQqgwbaTgbcXbneAeYXyQzRWDVianwZQQZNhnOYLXhxkXNPiUMoeFrJgDWSjMdGZgeFJFJTIbe"
aAAaaaaAaaaaAAAAAAaaaAaAaAAaaAAaaAAaaAaaaaaAAaAAAaaaAaAAAaAAaaAaAAAAAAaAAaaAaAaaaAAaAAAAaaAAAaAAaaAAaAAAAAaAAAAaaAaAaaaaaaaaaaAAAAaAAaAAAAAAaAaaaaAAAAAaaAaAAaAAaaaAaA = "HaqHVIpiYQSHytWiBXyzJWKsMACSjUAsLKJNVdNEwFAMDupkqmlcOCApIFHwcSFomevaSsOJEAZfwSH"
mkafbXlzofDzuZnuNLbiSjyNfCSGRoGdSaIcqcwgxYzMrOvMCZmSTNOVGuYjNuXNbKGBBJwkfawvmHf164 = "ILuplcOKTUrlTXUCwYsfIPSMQRsxPpusAOTerkjwsfWXFOKAUIiUgcYAwJJQVyKeBVbdcAuYaHwLwlQ"
lIlIlIIlIllIllIIlIllllIlIIlIlIIllIllIllIIIllllIlIllllIlIIIIlllIIlIlIIlIIIIlIlIIIllIIlllIIllIlllIlllllllllIIIlIIllIIllllIlIIlIllIIllIIlIllIIllllllIIlllllllIIllIIll = "drZXWJjFfCGqwVOEuxAgimRGdmBZIqqoFAgWNIuGVRvdCbCEnIgJdKnugVFlcaCsFxKIOSzqQqwLFbB"
O160 = 366
aaAAaaaAaAAaaaAaaaAaAAAaAAaaAaAAAAaAaaAaAaAaaAAaAaAAAAaAaaAaaAAAAAAAAaaAaaAAAAaaaaAaAaaaAaaAAAaAaaAaAaaaAaAaAaAAaAAaAaaaaAAAAaAaAAaaaaAAaAAAAAaaAaAaaaAAaaaAaa = "GWSEvQgUuOrmYpxZvpmcRDXbtnODybvGIZcYEvekZbyulgzqAeKvodUHAucVFOwJzjryjHSJiIFBCnU"
AaaAAaaaaaAaAAaAaAaaaAaAaAAaaaaaAAAAAAAaaAaAAaaaAAAAAaaAAaAaaAAAAAaAAAaAAaaaAAaAAaaAAAAAAaaaAAAaaAAAaaaAaaAAaAAAaAAaaaAaaaAAAaAaaAaaaAaAAAaAaaAaaAAAaaAAaaAa = 310
m16596004504133492154 = "UZmakPeQYOOQPQypqFLQLkRmxffKnklYjfWBieMcnuaOYhgujXOaGTLnoPMNbUALvEJqCHSBwfBZhRR"
IllIIIIIIlIIIllIIIIlIlllIlllIlIIllIIlIIIIIlIlIIIIIllllIIIIIIIIIIIlIIlllllIllIlIIllIllllIllIllIIlIIlIIIIIlllIllIllllIlIllIIllIlIIlIIlIllIlIIIllIlIIIIIIIl = 338
o165960045041319150 = "QkpSHwLcDUkJQFLxpzhXDbZDrRjuHymnTabgonHDHWUoutVUQpSflhpnPEbcquPQVnesvmBcpWOkjsn"
IllllIIIIlIlIIIIlIIllIlllIllIllIlllIIlIIllIllIlllIIllIIlIlIIIIlIIIIlIlIIIlIllIllIIIllllIlIIllllIlIlIllIlIlIlIIllIlIIIlllllIIIlIIlIllIlIlIlllllllIlll = "CBmvmkBUfXVPFgFyfCzFOcjHPhJGodwKRprLUAemfUZJJxWNnVukNolLeVdmxSXvojWfVHJqobhGZNR"
llIlIIlIlllIIIIIlllIIIIIllIllllIlIlllIIlllllIIIIIIIlIlllIIIlIllIlIIIIllIIlIllIIlIIlIlIlIllIIlIlIllIIIIllIlIlIllIIlIlllIIIlIIIIIlIllIlIIIIlIIlIIIll = 573
aaaaAAaaaaAAAaAAAaaAaaaaaAaAaAAAAAAAAAAaaAaaAaaaaaaAaAaaAAaAAAaAaaAAaaAaAAaAAaAaaaAAAAAaaaAaaaAaaaaAaAaaAaaAAAaaAaAaAAAAaaaaAaAAaaaAAAAaAAAaAaAA = 110
E1659600450412609142 = "nQIIoqBDHkJqZhMzyStTfkzDgnqTMRZSNobGaBgDhgQpjrctMXqXUTXsHNTUeuXFdxJIzsjirzZzowY"
BiJaLlGEUsPRVzfYLjIUnqqGYgZZmLHtCGPBqUHerqWtnKREVYMZmxcXHFSLWpdxsPzAipGsCpvmBNo140 = "SXTHvSQPFJPfSBbRisHDWBkrJAOQxAXSdnWrVYHDPkvlzNOxQGzwDWPAFbCKrUnsDgPQYwabwRIFrNK"
e138 = 35
x136 = 566
q134 = 853
aAAaAAAaaAAaaAaAAAAaaaaaAAAAAAAAaAAAAaAAAaaaAAaaaAaaAaaaaaAaaaaAaaAaAAAaAaaAAaAAAAAaAAAaAaAaaAAAAaaAAAAAaaAaAaaaAaaAAAaAAAaAAAAaaAAa = "PRoZVPCagwDAGpnXEiUeyJEuvRZQXCQOvARsOoIzrWvkZIiFruAxGVVOQBGoZBnHVAcfZPbDLkozLUm"
aaAaAaAAaAaaaaaAaaaAaAaaaaaAAaaAaaaaAaAaaaAAaAaaAaAAaAAaaaaAaaAAaaaaaAAAAaAaAaAAAAAAaaAaaAaAaaaAaaAAAaAAaaaaAAAaaaAAAAAAaAaaAaaaAa = 698
aaAaaAAAAaAaAAAaaaaaaAaAaaaAAAaaAAAaaAAAaAAAAaaAAaaaAaaAaAAaaAaAaAaaaaAAaAaAAAAAaaAaaaaaAaAaAaAaAAaAaaAAaaAaaaaAaaaAaaaaaaAaaAAa = 459
AaaAaAaaaaaaaaaAAAaaaAAAAAaaaaAAAAAaaaaaaaAAaAAAaaaAaaAAaaAAAAaaAAaaAAaAAAaAaaaaAAaaaaaaAaaaAaaaaaAaaaAAAaaAAAAAaaaaAaAaaAaaaA = "OJdlyOpLPOXwRTCEkoYrtBRfITLBlpQgVVngWNEjNUFYZUVYGBMNmaIPlFDGpvtBnTflTkUZERkruFv"
AaaAaAAAAaaaAAaAAAaaAaaaAaAaaAAaaAAaaaAaaaAaAaAAaaAaAaaAAAAaAaaaaaAAaAaAaaaaaAAAaaaAAaaaAAAAAaAAaAaAaaaaAAaAaaaaaAAAaAaAaAAa = 455
WSsRsTbdfQlCZumbtbqDPpaqaYVnfNErCaEFHRhePKznJTzEvYdRsCSjNQHGHPeqJWbSWoZNcUFNPOX122 = 633
p1659600450411607120 = 585
E1659600450411572118 = "iWdmltZqBXseFWjVzpJsyDzLWQZBpbPEnebiPVKeOHuuCzozIPxMngHIkkiGBrXbJDoymxWqWJnKfLT"
FeEzlyjYMSydsWcDdlRCccmWAEDMhxbdQdQiKEFkpcJtkwgTjpFNQwIHirsUqNxkRzGDqTiBewaPtBv116 = "FdFxPCNidKDKLmgJkimWHKMrbVNBLFuPBYaHXJxWbJDslwhLjLzOLUMtiNysedlphcFdmiWtwtBQqJx"
fowxxDktudKJYbtUusOWLQkGIoIkgvVvtJoMQbpnGSyGbKXxXNkfFgPPYQOPAUUCjaNLqNBdryDilaG114 = 183
aAaaAAaAAaaaaaaaaAAAaAAAaAAAAaaaaaaAaaaAaAaAaaaaaaAAAaaAAaaAaAAAAaAAaAAaaaAAAAaaAaaAAaAaAaaaaaAaaaaaaaaAaaaaaAAA = "nDIiTlgkMVcWaOLhOTWgPQAZgZbxImpOJqceYKrwTstcwNOZPsfUUUcpgNkQDNIzdUayLzuWjOeMbkp"
RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR = "EISKZFDDQClZmQrgIIDBcGCufdNMQzwLotowKnVBkLlrMbzUHIStUTMIuMOGruEUZMAUwosZNZDhcOV"
IIlIIlIIlllIIlIIIllIIIIllIlIllIIIIlIIIIIlllllIIllIllllIllIlIlIllIIllIIIIIIIlIlIlIIIIIllIlIllIIlIllIllIlIllll = 439
aaAAAAaAaaaAAaAaAAAAaaAaAaaaAAAaAAAaAAaAaAaaAAAaAaAaaAAaAaaaaaAAAaaaAaAAaaaAAAAaAaAAaAAAaAaAaaAaAAaAAAAaaA = "kEXDXVbzaQFPcDwBXGSvGDGQwSkocxvjPynXZDMqMMtEGDfAfCQgHosufkNnnhRFoyZSSXQsSykXOiZ"
Z1659600450411038104 = 398
H102 = 736
k1659600450411019100 = "RkgLtRafPvVDdWMlIBQwShHZETMTBIClGgbBEQHvaxhPKanyzReoGcNyVBZmSTSKfJeptSxvXaqzVvk"
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS = "OhyKllYCVpUUFYgetNcARLwahwZgTrUnVFOSduhsXdnfOJzhEXpTsNNPfYnCdyDozwmQlVSlJuutXes"
y1659600450410904296 = 205
AaAAaAAAAAAAaAaAaAaAAAaaaaAAaAAAAAAaAAaAAaAaaaAAAAAaAAaaAAaAaaaAAaaaAaAaAAAaaaAaaaAAAAaaaAAAAA = 562
AAaAaAAAaAAaAAaaaaaAaaAAAaaaAAaAaaaaaaAAAaAaAaaaaaaAaAaAAaAAAAAaAAAAaaaAaAAaaaaAAaaAAaAaAAAA = 469
AAaAAAaaaaAaAaAaaAaAaaaAAAaaAAAAAaaaAaaaAAaAaAAAAAaaaaAAaAAaAAaAAaAaAAaAAAAAAAaAaaaaaAAaaA = 371
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx = 294
aAaAaaaaaAaaaAAaaaAaAaaAaAAAaaAaAaaaaaaAAaAaAaaAAAAAaaAaaaAAAaaAAAAAAAaAaaaAaaaaAaAAaA = 500
g165960045041050184 = "lobDNJNyYgQjDecmdPrnNIwwRrrjqomKtKGjIZrCklBNoWGmZsFYoCbIxHfrYfhXhnthoHQHpBSBxEd"
w82 = "TVnEIyUzwbhDxgFIKDjYHBBcmyEGgnWBuYCJZLbcASAQNwSAvmyQgPyJMJFrKXnKwUjLRaOAYluTctd"
aaAaAAaaAAAaAaaAaAaAaaaAaaAAAaAaAAaAaaAAAaAAAAaAAaAAaaaaaAAaaaAaaaAaaaAAaaAaAAAa = "ZiKXBWMYNyEzUxJhkrIefKrqpWGkjwblVjiVBqcUVUxvWPPvSpqLvPOkdrbSkfoCoTSSJWxPZgHpwhF"
m78 = "uEuWAlpzORQwgoLLbqttGvVfxKDvHFqvkVazLRIrNdDuJRIHIKnMZtsdghOVpQwcfXkGkexrHglCTIX"
lIIllIlllIIIIllIlllIIlllIllIlIIIlllIllIlIIlIIIIlIIlllIIlllIlllllIlIlIIlIlIll = "sxFiEcUKfQqNdHLKUuouVDOSGqqjJDBEeOmfYbbhdSFDborKwAhfOgLuTxfmRImUrCJekJCnVXicfVU"
aAaaAAaaaaAaaaAAAAaaAaAAAAaaaaAaAAAAaaAAaaAaaAaaaaAaAAaaAaAAaAaAaAAAaaaaaA = "KWOHLWeZyUUsgfMGUASteMbfgXZXFkWzeQaXyxzpQKuuhwHjvbwJtEkGZZBdzOoxTulBzxSdhJdRIsp"
hNIHHbDksxFpBLpVoDylkkAGYoOSCJWVszaRpALbvTpMyNezXwCQRtiYXDXFZPWHqusdEzkVFLNHnxR72 = "qsXWKwXCCtqrqwwowycITdqMsQVWWdRslEGrLGNOOFpsieBonpKhOKeyWrDFASdaxhcKnnEFMojzXDj"
IllIIIIlllIllIIllllIlllIllIlIIIIIlIIIIIlllIIIlIlllllllIllIllIllllllIlI = "DtBXsQQnYAZIJgdcyGzSySwyzckIUTgfCqPIVxUFFqEXUQBmzbGBkXmicqbDJAlEsoXncFSGKauNqEE"
AAaaaAAaaAaAaaaAaaAAAaaaaAaAaAaAaAAAAaAaaaAAAaaAaaaaaAAaaaAaAAAAAAaa = "xMYUsLPYwJrXroHAcUFRkpFlxSeBkgRwDFJDQdJvEkPQxOViZcbXIoOQGelrgnLMfXYQpVxnEqnNnKo"
RIyoqNnuPcQEhCSXQSQtEsUiPDJwFpcBOmusJNgBfWFkXGEGsbcIfHLnpACAMEBEidhBCkyuexAsoAg66 = "IrvEZrmhsxNVTGKeWeuLuGtiTgezoyupsrhDfIhbPdppELeBRuMjwQTTSjbVNaCyNkiDyqpqbSwKlDW"
IIIlIlllllIlIllIIIllllIlIIIlllIlIIIIlllIIllIIIIIIlIlllIllllllIIl = 198
eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee = 143
DJTWRKWSEwsXddjhzBRyWZtOcUBihrYgHPVuRHynAmKySEnNBPrjUsIfrmVFBuLUBYCHCnadljdhTre60 = 444
lIllllIIlIllIIIIllllllIlllIIIIIlIIlIlIlllIllIlIIlIllllIlll = 412
p56 = "pETDlMogkkvkTVdqDxoTPGwqbomASDLhxhFHflljOqhyxJCDZTHZlSiIlEgbvPpwaVycYxEMgKhkESe"
VaXdqxYOoHMOiUOSmGwfTtoslYQmhqTjuvNKKdHNLMxXoMYTFDrONXcdHshftaEqrrPxSJeAMPOSNpq54 = "KRVjOmAKlJBTqXoQccBPMHqfcilbTAXdqRsbwDomvTCYBHiYGffPhenwpiTWqDqnWuguDnGjGXLBkVK"
ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ = 241
o165960045040924750 = "yDszilwlKXWgJPBbhTzYRWnPTAocufNoJvtkWGUsQAGySJxBUPAnBZPGkcGwFyyTVERJGLcaorqWUxx"
K48 = 250
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA = "tQMFtqhcjIAROtZweMKSYXjOgeyWUhzDUtgcrIhqfVmcMlpYYvuVgeqxJYenOdHXugAEmNPbyiRASek"
llllIlIlIIIIIIIIllllIlIlIIllIIIllIllIllIIlll = "peMzKGrywvKUyZehfjhvkGNjouffCvDjcJSVvjIryVSKdhwNqPTTAUQPRXWOLiEtKiCDSIwXTyWIcLM"
lIIlIlIIIIIIIIllIlllIlllIlllIIllIlIllIIllI = "UWzXjyTgKAEpAOPeRohFxhHURYlugPsywXaMMnBzpaCSUBQNdStohyaGVIUCxYPrIplIUKKnvpPNhxp"
V1659600450408944140 = 463
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE = 205
e165960045040889836 = "ksGvBNoOgggRnIEzKvtwUJUgdlNlesJUrqCUuyNZjucPoEMWvsdhdemwaGVsMlyvtBPHqoviKZHnJGi"
CwUblfrTxzfIbrDJcJxHokXCpUnJoEYhQOhdnweenOsRfAZWgbabHNRkThZLlUljlyLlkKwKMjuXlnR34 = "aHcBqOIJGaBDSuFGMAlWERxoRjxIiVWTSGwdrFrPjSTaMlVaLkpvSVZZHYYOTojNLSbxyFmwjqLIJSy"
s1659600450408743932 = 426
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhh = "vqGiOPuNloECtTwnOzzLGCGSUjvGmcMAwPLRnymnIcQtaPEbNftfuolyQcPSfdeWSPfVAaJxHAAmUwG"
AAaAaaAAaAaAAAaAAAaAaaaAAAAA = "JZRVbbOCkIpfCPdGZXXZbCpjpAKlTkPwLGgQAERCgFrEYkWXqQjrLlGhZtbdelAaTtpuNtWzVoBTtVT"
P26 = 95
C24 = 351
Y165960045040849422 = "vIZARnsgKMTXOdISRJzKRcZVnXaomABdWWbKIBcEWcIRliQAmHXnbHQNWdQvlNSqezCrDtsqPVZBEjh"
JswHyolOiIbkObuzKyYvjGWsBXrchyHFMsXMjCOtfsZDnwnWVPHTUKceWmSLEgEkdXnbGqkaXOKRsDR20 = 628
J1659600450408387218 = "IupRpzDFlxeeiEOrTBtsADeYqzlVewUmoshujMrgXqZglNkcbPFnLdEecKAwzJVoysDMjpgXVRTjuzU"
HSXdfFkxhbAHlMeEygxofLLBAjAvsJSXOIUSPGEhfKXwQeFnEsYoPjGThumbneBHqLaKrZxPsUXSroP16 = 465
wwwwwwwwwwwwww = 315
RbUENqUEylQsHXLnAuAvpcgVERBUKkwwxWKgpapjHcpAKOcfnvFGgtSlsaBbOdORcUHafgZCYKTVTwz12 = 232
tryZAjTUOqoUeppnkDfWXaHJLatHKXsNDciuaXCwnHHROrCerjuZQQhSAVMTYbwlDsOLzMFdBxKnRru10 = 236
U16596004504080618 = "ARBzuYjoHjezroQVEFChtKnaMdVALsIiMIhDUPPrZSGcipxMPZFYlibtRLMRDuIgBQdaZzfClMZYPeC"
lIlIIl = 157
V16596004504079514 = "tUnPqYSHfPWxTsFzztRVoiIlmfhRCLpgXQhoMRbjplcGmHSHyWewtDwkBWnLsILAwtSLDZYjMUZFkme"
ll = 44

from pyblinkpico import *
import time


# CONSTANTS
j16596004503958561 = 200
TT = 100
OVsHkQFNnCgDqyRVbcSAamAJfctoQBuhgZtTkLFeocKFtbLbSXTcaYlereLuBgnLbRPIQxDBwbCPzFl3 = 1
llIl = 0
b165960045039700985 = 8
AAaaAa = 50

# GLOBALS
llIllll = b165960045039700985//2 - 1
ptiVrgxytFpJQpSDSRvcyStmfJiYWidFznGSPReVqpZRtlvVLldufVxctobZbRVzvcyPgMrKstHsIOS8 = 0
eeeeeeeee = [llIl]*(b165960045039700985*b165960045039700985)

# Tick routine
cccccccccc = {}


def tick(ms, callback):
    if (ms not in cccccccccc):
        cccccccccc[ms] = 0
    if time.ticks_diff(time.ticks_ms(), cccccccccc[ms]) > ms:
        callback()
        cccccccccc[ms] = time.ticks_ms()


def getPixel(llIllll, ptiVrgxytFpJQpSDSRvcyStmfJiYWidFznGSPReVqpZRtlvVLldufVxctobZbRVzvcyPgMrKstHsIOS8, AAAaaAAaaaaaaAAaaAAaaAaaaaaAaAaaaAa):
    if (llIllll < 0 or llIllll > b165960045039700985-1):
        return None
    if (ptiVrgxytFpJQpSDSRvcyStmfJiYWidFznGSPReVqpZRtlvVLldufVxctobZbRVzvcyPgMrKstHsIOS8 < 0 or ptiVrgxytFpJQpSDSRvcyStmfJiYWidFznGSPReVqpZRtlvVLldufVxctobZbRVzvcyPgMrKstHsIOS8 > b165960045039700985-1):
        return None
    return AAAaaAAaaaaaaAAaaAAaaAaaaaaAaAaaaAa[llIllll+b165960045039700985*ptiVrgxytFpJQpSDSRvcyStmfJiYWidFznGSPReVqpZRtlvVLldufVxctobZbRVzvcyPgMrKstHsIOS8]



def setPixel(llIllll, ptiVrgxytFpJQpSDSRvcyStmfJiYWidFznGSPReVqpZRtlvVLldufVxctobZbRVzvcyPgMrKstHsIOS8, aAaAAaaaAAAaAaAaaAaaaaaa, AAAaaAAaaaaaaAAaaAAaaAaaaaaAaAaaaAa):
    if (llIllll < 0 or llIllll > b165960045039700985-1):
        return
    if (ptiVrgxytFpJQpSDSRvcyStmfJiYWidFznGSPReVqpZRtlvVLldufVxctobZbRVzvcyPgMrKstHsIOS8 < 0 or ptiVrgxytFpJQpSDSRvcyStmfJiYWidFznGSPReVqpZRtlvVLldufVxctobZbRVzvcyPgMrKstHsIOS8 > b165960045039700985-1):
        return
    AAAaaAAaaaaaaAAaaAAaaAaaaaaAaAaaaAa[llIllll+b165960045039700985*ptiVrgxytFpJQpSDSRvcyStmfJiYWidFznGSPReVqpZRtlvVLldufVxctobZbRVzvcyPgMrKstHsIOS8] = aAaAAaaaAAAaAaAaaAaaaaaa


def getPixelAround(llIllll, ptiVrgxytFpJQpSDSRvcyStmfJiYWidFznGSPReVqpZRtlvVLldufVxctobZbRVzvcyPgMrKstHsIOS8, AAAaaAAaaaaaaAAaaAAaaAaaaaaAaAaaaAa):
    ttttttttttt = getPixel(llIllll, ptiVrgxytFpJQpSDSRvcyStmfJiYWidFznGSPReVqpZRtlvVLldufVxctobZbRVzvcyPgMrKstHsIOS8-1, AAAaaAAaaaaaaAAaaAAaaAaaaaaAaAaaaAa)
    gvTHFqTdyMIcbdNKocPaqsCwjxThggGHkAyNLAKulNRmrWCxhUkwDtStfZAxPQDDSnKIffrtiRngcOX12 = getPixel(llIllll+1, ptiVrgxytFpJQpSDSRvcyStmfJiYWidFznGSPReVqpZRtlvVLldufVxctobZbRVzvcyPgMrKstHsIOS8, AAAaaAAaaaaaaAAaaAAaaAaaaaaAaAaaaAa)
    J165960045039987613 = getPixel(llIllll, ptiVrgxytFpJQpSDSRvcyStmfJiYWidFznGSPReVqpZRtlvVLldufVxctobZbRVzvcyPgMrKstHsIOS8+1, AAAaaAAaaaaaaAAaaAAaaAaaaaaAaAaaaAa)
    llIllIllIlIlIl = getPixel(llIllll-1, ptiVrgxytFpJQpSDSRvcyStmfJiYWidFznGSPReVqpZRtlvVLldufVxctobZbRVzvcyPgMrKstHsIOS8, AAAaaAAaaaaaaAAaaAAaaAaaaaaAaAaaaAa)
    return {"ttttttttttt": ttttttttttt, "gvTHFqTdyMIcbdNKocPaqsCwjxThggGHkAyNLAKulNRmrWCxhUkwDtStfZAxPQDDSnKIffrtiRngcOX12": gvTHFqTdyMIcbdNKocPaqsCwjxThggGHkAyNLAKulNRmrWCxhUkwDtStfZAxPQDDSnKIffrtiRngcOX12, "J165960045039987613": J165960045039987613, "llIllIllIlIlIl": llIllIllIlIlIl}


def addCurrentToPixels(llIllll, ptiVrgxytFpJQpSDSRvcyStmfJiYWidFznGSPReVqpZRtlvVLldufVxctobZbRVzvcyPgMrKstHsIOS8, AAAaaAAaaaaaaAAaaAAaaAaaaaaAaAaaaAa):
    X165960045040105715 = AAAaaAAaaaaaaAAaaAAaaAaaaaaAaAaaaAa[:]
    setPixel(llIllll, ptiVrgxytFpJQpSDSRvcyStmfJiYWidFznGSPReVqpZRtlvVLldufVxctobZbRVzvcyPgMrKstHsIOS8, OVsHkQFNnCgDqyRVbcSAamAJfctoQBuhgZtTkLFeocKFtbLbSXTcaYlereLuBgnLbRPIQxDBwbCPzFl3, X165960045040105715)
    return X165960045040105715


def gameOver():
    return getPixel(0, 0, eeeeeeeee) \
        or getPixel(1, 0, eeeeeeeee) \
        or getPixel(2, 0, eeeeeeeee) \
        or getPixel(3, 0, eeeeeeeee) \
        or getPixel(4, 0, eeeeeeeee) \
        or getPixel(5, 0, eeeeeeeee) \
        or getPixel(6, 0, eeeeeeeee) \
        or getPixel(7, 0, eeeeeeeee) 

def llIllIllIlIlIl():
    global llIllll
    if (llIllll == 0):
        return
    J165960045040174217 = getPixelAround(llIllll, ptiVrgxytFpJQpSDSRvcyStmfJiYWidFznGSPReVqpZRtlvVLldufVxctobZbRVzvcyPgMrKstHsIOS8, eeeeeeeee)
    if (J165960045040174217["llIllIllIlIlIl"] == 0):
        llIllll -= 1


def gvTHFqTdyMIcbdNKocPaqsCwjxThggGHkAyNLAKulNRmrWCxhUkwDtStfZAxPQDDSnKIffrtiRngcOX12():
    global llIllll
    if (llIllll == b165960045039700985-1):
        return
    J165960045040174217 = getPixelAround(llIllll, ptiVrgxytFpJQpSDSRvcyStmfJiYWidFznGSPReVqpZRtlvVLldufVxctobZbRVzvcyPgMrKstHsIOS8, eeeeeeeee)
    if (J165960045040174217["gvTHFqTdyMIcbdNKocPaqsCwjxThggGHkAyNLAKulNRmrWCxhUkwDtStfZAxPQDDSnKIffrtiRngcOX12"] == 0):
        llIllll += 1


def down():
    global ptiVrgxytFpJQpSDSRvcyStmfJiYWidFznGSPReVqpZRtlvVLldufVxctobZbRVzvcyPgMrKstHsIOS8
    if (ptiVrgxytFpJQpSDSRvcyStmfJiYWidFznGSPReVqpZRtlvVLldufVxctobZbRVzvcyPgMrKstHsIOS8 == b165960045039700985-1):
        return
    if (canGoDown()):
        ptiVrgxytFpJQpSDSRvcyStmfJiYWidFznGSPReVqpZRtlvVLldufVxctobZbRVzvcyPgMrKstHsIOS8 += 1


def canGoDown():
    J165960045040174217 = getPixelAround(llIllll, ptiVrgxytFpJQpSDSRvcyStmfJiYWidFznGSPReVqpZRtlvVLldufVxctobZbRVzvcyPgMrKstHsIOS8, eeeeeeeee)
    return J165960045040174217["J165960045039987613"] == 0


def drawPixels(AAAaaAAaaaaaaAAaaAAaaAaaaaaAaAaaaAa):
    for i in range(0, len(AAAaaAAaaaaaaAAaaAAaaAaaaaaAaAaaaAa)):
        llIllll = i % b165960045039700985
        ptiVrgxytFpJQpSDSRvcyStmfJiYWidFznGSPReVqpZRtlvVLldufVxctobZbRVzvcyPgMrKstHsIOS8 = i//b165960045039700985
        aAaAAaaaAAAaAaAaaAaaaaaa = getPixel(llIllll, ptiVrgxytFpJQpSDSRvcyStmfJiYWidFznGSPReVqpZRtlvVLldufVxctobZbRVzvcyPgMrKstHsIOS8, AAAaaAAaaaaaaAAaaAAaaAaaaaaAaAaaaAa)
        display[ptiVrgxytFpJQpSDSRvcyStmfJiYWidFznGSPReVqpZRtlvVLldufVxctobZbRVzvcyPgMrKstHsIOS8, llIllll] = aAaAAaaaAAAaAaAaaAaaaaaa
    display.show()


def rowScore(ls):
    XXMlsvLKuzSLXifGeUldXVzXZjOzzToAfOmxjwInJvvaygvDHOkYmbcTQsvbrubwGMwelDjYYFqVLXO25 = 0
    for l in ls:
        XXMlsvLKuzSLXifGeUldXVzXZjOzzToAfOmxjwInJvvaygvDHOkYmbcTQsvbrubwGMwelDjYYFqVLXO25 += l
    return XXMlsvLKuzSLXifGeUldXVzXZjOzzToAfOmxjwInJvvaygvDHOkYmbcTQsvbrubwGMwelDjYYFqVLXO25


def lineFull():
    for i in range(b165960045039700985, 0, -1):
        aAAaaaaaAAaAaaaaaAAAaaAAaA = i-1
        if (rowScore(eeeeeeeee[aAAaaaaaAAaAaaaaaAAAaaAAaA*b165960045039700985:aAAaaaaaAAaAaaaaaAAAaaAAaA*b165960045039700985+b165960045039700985]) == b165960045039700985):
            return aAAaaaaaAAaAaaaaaAAAaaAAaA
    return None


def lastLineFull():
    return lineFull() == b165960045039700985-1


def removeLastLine():
    global eeeeeeeee
    jjjjjjjjjjjjjjjjjjjjjjjjjjj = b165960045039700985*[0]
    jjjjjjjjjjjjjjjjjjjjjjjjjjj.extend(eeeeeeeee[0:len(eeeeeeeee)-b165960045039700985])
    eeeeeeeee = jjjjjjjjjjjjjjjjjjjjjjjjjjj


def newBlock():
    global llIllll, ptiVrgxytFpJQpSDSRvcyStmfJiYWidFznGSPReVqpZRtlvVLldufVxctobZbRVzvcyPgMrKstHsIOS8
    llIllll = b165960045039700985//2 - 1
    ptiVrgxytFpJQpSDSRvcyStmfJiYWidFznGSPReVqpZRtlvVLldufVxctobZbRVzvcyPgMrKstHsIOS8 = 0


def sadFace():
    display.fill(0) # clear
    
    for aAAaaaaaAAaAaaaaaAAAaaAAaA in range(2, 6):
        display[aAAaaaaaAAaAaaaaaAAAaaAAaA, 0] = 1
        display[aAAaaaaaAAaAaaaaaAAAaaAAaA, 7] = 1
        time.sleep_ms(100)

    for column in range(2, 6):
        display[0, column] = 1
        display[7, column] = 1
        time.sleep_ms(100)

    display[1,1] = 1
    display[1,6] = 1
    display[6,1] = 1
    display[6,6] = 1
    
    display[2,2] = 1
    display[2,5] = 1
    
    display[4,3] = 1
    display[4,4] = 1
    display[5,2] = 1
    display[5,5] = 1
    display.show()


def newGame():
    global llIllll, ptiVrgxytFpJQpSDSRvcyStmfJiYWidFznGSPReVqpZRtlvVLldufVxctobZbRVzvcyPgMrKstHsIOS8, eeeeeeeee
    llIllll = b165960045039700985//2 - 1
    ptiVrgxytFpJQpSDSRvcyStmfJiYWidFznGSPReVqpZRtlvVLldufVxctobZbRVzvcyPgMrKstHsIOS8 = 0
    eeeeeeeee = [llIl]*(b165960045039700985*b165960045039700985)

    display.fill(0)
    display.brightness(AAaaAa)
    drawPixels(eeeeeeeee)

def updatelogic():      
    global eeeeeeeee

    if (canGoDown()):
        down()
    else:
        eeeeeeeee = addCurrentToPixels(llIllll, ptiVrgxytFpJQpSDSRvcyStmfJiYWidFznGSPReVqpZRtlvVLldufVxctobZbRVzvcyPgMrKstHsIOS8, eeeeeeeee)
        newBlock()

    if (lastLineFull()):
        removeLastLine()


def updateInputUI():
    # Get current block and eeeeeeeee and draw them
    AAAaaAAaaaaaaAAaaAAaaAaaaaaAaAaaaAa = addCurrentToPixels(llIllll, ptiVrgxytFpJQpSDSRvcyStmfJiYWidFznGSPReVqpZRtlvVLldufVxctobZbRVzvcyPgMrKstHsIOS8, eeeeeeeee)
    drawPixels(AAAaaAAaaaaaaAAaaAAaaAaaaaaAaAaaaAa)

    # Update current block position
    if (button_a.is_pressed()):
        llIllIllIlIlIl()
    elif (button_b.is_pressed()):
        gvTHFqTdyMIcbdNKocPaqsCwjxThggGHkAyNLAKulNRmrWCxhUkwDtStfZAxPQDDSnKIffrtiRngcOX12()

def waitForNewGame():
    while True:
        if (button_c.is_pressed()):
            newGame()
            return
            
# main
newGame()

while True:

    # Game Over
    if(gameOver()):
        sadFace()
        waitForNewGame()

    tick(TT, updateInputUI)
    tick(j16596004503958561, updatelogic)



A = 606
QmXPUbstSLdJuzehTxhbXltELpmyJsWhaQHjeTVAURstKpjngyyNiBlqHcLbZXhbmlRpOUvdpTOUvtJ3 = "FNDeTQHOTImBPMKSuEKTnSwPCgaNmyfqnbtkXqMHvKJvRyyhoPzSaphndHGntIYGTTySelQJojXyVfB"
llIII = "jUbuiCukWONSFukOIMkONSyqmUrLThJuZfVrfKGcePaDnYNyxinwVXQnGxAlgpOWlLTRgCbggHHeBCs"
szWSTPolojZihabFRbfHDvKOrBxbojXhmOJhgmCtVLKcBixBWgKEGvVAqvVmudKEdxOWDizdkEYyyYZ7 = 730
k16596004504080969 = "SveoAxMOKJIsgtozkVeMqepXBXaWRmjqCwNzwLhJbzOzvjwxbskZdmMSVtxlpdSYOOQuMraKSPMGtcz"
aMxYYMunFMtzpwkFALAeUdYABsmkEARGPFcXOBRzIArerjMFgGWDncJAFtZOHFvUXlniTWjqYysQBJK11 = "EbJOOHhOiDsCZWKgsMCMgaSRvzQhyrekcWDlwyWhJPMfQUtWdSZDdpuDXHzzwwkoRWFgXOtnHefwEgk"
z13 = "THsaLQWNDkwSnpyHbDtBgVVxiLwiCVyYWqcCbLsZuxoYWbyGHoxYTHqeqMNfIQmwPkYpxVQykhBYpZL"
l165960045040829115 = "ImkoVYsxKYmPOoEqVouzALRmtLTDaaXlbXICXRImCBOtZksMLqSiVltTTznmTHCbCogrMcKotRrwcpc"
pnkGJNwrqNblyfZOUtfdhLAhIjqeaPyqqEaVWlaGiwKFBXbdctlISuvgTXnaIosxASKHRCvbegBPqiA17 = 853
X19 = 897
s1659600450408460121 = "yOleLgLskzxOgTIBKcKXXlFYKVBcbPilaIgYaQkrRmVwJJoUyHEUAqRaYLYZAvluKUnGgQNSKYiNFej"
g23 = "JVlLMudYtspzzKuPmpamWJQReJjHiflPijHihMfQtsNrxDEsTMHkcyRqruFFqHkNUqecGxCbtJdgErr"
E25 = 357
R27 = "BITsYCOAzCJaOzhvehaQeNUEwYamtWaAKzeEVwHDVqRrTaWXBDNYPdDcjzMoTNicSbrgjKfcjBEvkLw"
mpQkmdBBONQTvsWReiVeewsfTonMQHhqwmWljoyreMaHZTYuhEYqyKxhuKvlqpAZacKlTRKLVKtcPDD29 = "dihUxLWRMNpdCawwyUXJMqAnwSefKOAxzrCjgTIrjUwqrYExOENTlDxSpxzBSLiWehhIPhgZjazHnga"
M16596004504087431 = "aDeWZOPGzSjRimbfbnMdmVhxbYIwetDUDMlEsUPFHkaqGUYkjbadJHTDfRtgPZgXooQRIUVhHGRnLXB"
lIIIllllIIllIllIlIllIlIllllIlIlIl = 349
AAaAAaAAaaaAaaAAAAAAAAAaAaAaaAaaaaa = "vWJkWNyQsiSsBjCoTOckGPEaJgUPWEKqMiePCdTFLlKhjfIwetMmBXgXcDkhzBwCFlhugIMhACnvzYB"
q165960045040890337 = 98
kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk = "bJIYVDfmoQwSSAbrQjyRBOeCanLfrwMNLDyzJPKmIaoGgqCepbIhFknqVwScIbgflsrhLLpZmfNbewx"
wfDXGCjJkrDKJequmWAPMSCkNhBuVzFOloMBdalgrdjJuxINUWgvjyzsCPFpVnaDTZLMWAEBlCWjKFz41 = 522
e165960045040902943 = 656
X45 = "khExgkXYmgBXotIltHPYqWVwJUeeirmFLLJExdwBEVEOViMqCfjxTzBxFINCtLFLiwHExKRevlhIJXp"
a47 = "rIlwnezyJKvjZvCkiKxodGOOXXIXFPtLGtschoxXkHEOCXoQlvlyoUsIOzOfAoNKMYBzIKEfJlNhwiR"
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL = "WxwWwULWaRmymIMdKNbOVoXEFUxLXtCqqjHRkWBPwqyExaSrwKVgjdoSvgUyiLNAPhuRbZoyHSXeJYY"
H51 = 609
IlIllllllIIIIIIllIlIllIIlIIlIllIIlIlIIIIlIllIIlIlIIIl = "mJvwNBMxsWmxedkpDqHKPkKfeJGzuQNSlIWLnNiROiGoXbArpItSAoPwTOAebtauVOxMIPxGYzHEdQz"
IIllllllIIIllIllllIlIIlIllIllllIIIlIlIlIIlIlllIllIIllII = 290
QlxbYzAMBxUpaYmqlaeoUnWMacnrvOTbHjawwaFjokxcbVxdqOLbENAbKfOdoicsTYeDmFGAGhqCGfR57 = "ZPtxWLrbMbIYMIwwDVbVHqclgDoPnZwBEDssLFbJXBZWagJSLFKcxmoTHHOghNLSZvANjBclHzUgEbc"
XjuinaFhfnUqsGCvuHPETEvPNRcCzhoAEmBkPoiTFxWmbonsaFJuNxhLvFFMKQtDHgIUFyiJuJWaRCV59 = "IGrgXFmpBjZMEOjGclGmIdpTAWSNPjngkpvfeZmMLEKhktHGyWlgJYUQrdkPFlmELTIqELdPhyUCYYj"
RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR = "ZYBsxoWMMEkpIVCoLgEzVVoIEXzGwRITcsyqTonjYinVKSkLciKjiyvRjopXYjmTugFcfBeEfwZfBkq"
aAaaAAaAaAaAaaAAAAaAAaAAaAAAaAAAaaAAAaAAAAAAaAaaaAAAAAaaAAaAAaa = "MpEfbYGfjVarWovEGySbzuOlCMNsCBgRljXOyOpymmwTsQQnFpXecGaBJlDajdLjXiKcsZgOLjjOYtk"
p65 = 265
rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr = 515
aaAaAaaAAaaAaaaaaaaAaAAAAAaaaAaaAAaAaAaaAAaAaAaAaaAaAaAaaAaAAaAAaAAaA = "RtjJrOwqhjpzYiTArIsQTCGrOhSCzzUilcTQkvCMJPqthyMzPeVjluCLNaJkcdeiSMVfpLQiIimsiML"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO = "MOZgayYbyLWZoysgFPMxclWPqZWmPjDXRgxNBAEOkrMirCjAYjuiNLzkaaCJzXOlMSwjgaGHhQLxvYD"
A165960045041005273 = 571
AAAaaaaaaaaaaaAAaaaaAAaaAaaaAaAAAAaAaaAaaaaaaaaAAaAaAAAaAaaAaaaAaAaaaaAAAAA = "ismYsIoiIlkPAPDZnhWxQxnCuEZQQayMvrIDFGnLRCaZDUgFEcAJfpTBQspCtykpGiWJMstZGjPmzLO"
Q165960045041023877 = 861
V79 = 372
aaAAAAaAAAAAAAaaaAAaAAAAaAAaaaaAaAAaaaaaaAaAAaAaAaAaaaAaAaaAAAaAaaAAaaaaaaaAAAaAa = "xHiuNskAWvOzcUKuBTmptiHZuUceFOpfZXqSVPHAPNjINyFwacOswljxvcnwwYfYfhUYhbQfkmmzvLa"
llIllllIlIllIIIIIIIlllIlIIIIllIIIllIIIIIlllllIlIIlllllllIIlIIIIIIIIllIllllIIlllllll = 814
S85 = "VdjvDbSYIOHPnKMJfELkelrOIBVkdvSAPnZwrFswpkIhNQfyNgjtanpMwRZNMhjPNebaOczzBTQHnbD"
E87 = "LBwcopxFSzSBSeZwwtAhuYkDSbQEMyCphOjzWkBVhdxHuGfWJtuDKTqwPLsaOIUfojOsrsrwvsYvpnw"
aAAaaaAAaaAaaaAaAaaAaaaaAAaaAAAaAAaAAAaAAaAaAaAAaaaaAaaAaAAaaAAAAaaAaAAaAAAAAAAaaAaaAAaAA = 362
llIllIlIlIlIIIlIlIlIIllIIllllIllllllIlIIIIIllIlllIIIlIlIllIIIIlIIIlIIlllIIIllllllllIIllIlII = "euqdysjWHrKpycZvGRHGszeyHcecSPsXGaTiVwfwhyhctmlVGuHGtMxaYadhAzjtKVKmSpRUwWDPzZx"
IllIIIlIlIllIIlIIIlllIIIlllllllllIIIIIIIllIIIlIIllllIlIIlIIIlIIIIlIllllIlIlIllIIIlIlIIIlIlllI = 307
aaAaaaAAaaaaAaaAAAaAAAaaaaaaaAAaaaaaAAaaaAaAAAAAaAaaAAaaAaaAaAaaAaaAAAAAaaaAAaaAaAAaAAaAAAAAAAA = 390
d165960045041091197 = 161
lIllllllIIlIIIIIIIlIIlIllIIIlIlIlllllllllIIllIllllIlllIIIllIIIlIIIIllIIlIlllllIIIlIlIIllIlllIlIIIIl = 613
ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ = 335
D1659600450411034103 = 30
G105 = "mQMZIqaTnaanWgQyGHyRnnVoecaQuOehvwCqPsxaKFDJelyvRcTvCeBSuEukEagLxbYpcWdEoueNfGz"
AaAaaaaAaAaaAaAaaAaAaaaAaaaaaaaAAaaAaAAaaAaAaaaAaAAaaaAaAAAaAAAaaaAAAAAaaAaAaAAAAAAAaaAAAaaAAaAAaAaaaAaaaAa = "ABoiszhirXWyNTEKBoyAJJrKsfnlTCQRrNZYcfvGmzteUyaQRgzqlyTqZKaZvynzJaVziPxtODWgjeC"
C1659600450411291109 = "AbLukRxSqRULgXIMXjpmyGqpXaTCShCkhDGMHfgFnVcUZlPFXZNYRUZuyYPjvhkWvpdbChauAILOscm"
Q111 = 371
r1659600450411406113 = 431
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo = 446
A117 = "HHdZClrnrBihodudJgFxHgUOKhbUrolNGCEPnpIFMKkJYfmJXmJKqFEoojTUusNmyUEjYpkhIFoNBsw"
cQniURAgzfuvyeyCrVDcUbyaNCdDAhoHstCYVMlhvzfNlCCEiivaJHcmiDFmusOhRphRrGXFJzxCyjU119 = 341
L16596004504116411121 = "xeNCgrnnNHuCQpvtfKEGDxtbHtdkLlvaLLZywZftIXthawyslGjZbUrGxTSKaiTCWPdJwrGpsgncdFe"
S1659600450411677123 = 389
e1659600450411747125 = 410
S165960045041183127 = 512
NfWjPpLKPstEWYbcZUaOfDzMgObHoRyPXwuDzaXyCjlorBbqrJVvzBmJkXZpdhGMiueaSjHwmUzXnCG129 = 550
a131 = "UrHulcJUrcYFvrkVnBrvZUMnoUNchJHtUuPAKrMptynQsOSwnfskkNvLaYqFeqMKnZTCnjFJXTRYvGG"
j133 = 468
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh = 431
aAaaaAAAaaAAaAaAAAAAaaaaAaaaaAAAaaaaaaaaAaaAaAaAAaaaAaaAaaaAaaAaaAaaaAaAaaAAAAaAaaAaAAaaaAAaAAAaAaAAaAaAAaAAaaAaaaAaAAAaAAAAAaAAAAAAAAAAA = 310
e1659600450412435139 = 755
X141 = 412
yJcosSfFMdjiudhPZExZhztHcKxKSQbbezTZYLKBBCUNoYvaBRmeaBoLpCytzPojmPgPLhDPIRoLNvg143 = 219
V1659600450412836145 = "RoCIBhnYXWJOXOXWChkXkJLjalRtAEqhtLMxAOOWKygxwJFcceDwFKClNkyqpWAGjeWJfyhZImMgWiA"
z147 = "sooiHuHyEremKcWyZZaMZonMleEvJipjHykVvqAZcSiJXBTQxEAolPYgUMDgCXrkEGoMDvmjewDhMUU"
yJVPDvjEecjQuuNmOvvnHFnaOfZgxLstJQkYAAQFtcEcgUPEyOTpNaaEmCaFkqRFiImgCGtpAcFNrIm149 = 336
I1659600450413197151 = 723
AAaaaaAAaaaaaAAaAAaaAaAAaaaaaaAAaaAAaaAaAAAaaaAaaaaaAAAaAAAAAAAAaAAaAAAaAaAAAaaaaaAaaAAAAAAAAaAaaaAAAAAAaAAaaAAAAAaAaAAAAaAaaAaaAAaaAAAaaAaAaAaAAaAaAAaAa = 656
AaaaaaaaaaaaAaAAAaaAaAaaaaaaAAaAAaAAaAAaAaaaaaaaaAAaAaaaaAaaaAaAAAAaaaaaAAAaaaAaAaAaaaaAAAaAaaAAaaAAAaaaaaAaAaAaAaAaaAaaAAaaAaaaAAaAaaaaAaAAaaaAAAaaaAAaAAA = "wzSQpgNaFulqMhbaLKVZpCgijXfxkziawKYXHfzAvmzbQCFWySlbtwICduwbDcEDvKQeqxGjiywTnFp"
sMHKVwUhcuxeZbVyfGSkABCtKmQZJmHuirJcCoVbnzKDvfNtLAbBvdvzsZxFbyAVKHTzNGlkNfdHEGu157 = 229
Y16596004504137201159 = 511
V1659600450413759161 = "kkOGtZZbmTJkVVYwRYRxNcghsmoiEHPcBzAIhvXgkNuvfeWQYxWQmNJbEizItdEyMJvIKQueFMxlfSz"
M1659600450413857163 = 562
UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU = 491
L167 = "WxJAucrcOthacGwwIsFNIlJfLAsTwTGfbqgoTFPZRJpdKnSIRGZsNiGzePxTbWYZGBKEfMdweDnEbbn"
AAAaAaaAaAaaaAAaaAAAaaAaaAAAaAaAAAAaAaAaaaaaaAaaAaAaAaaaAaaaAaAAaaAAAAAaAaaaaaAAaaAaAAaaaAaaAaaAaAaaaaaAAaaaAAAAaaaaaaAAaaaAaAAaAaaaaAAAaAAaAAaAaaAaAAAAaAaaAAAAAAaaAaaaA = "oXMbGKSYiIoggVCFkbshMnXxaDhihWzTHqFnZgqyWCBEqjQzwggGNJYiDqtccMoIISGjcveWIkUcNje"
O1659600450414242171 = 538
M173 = "PUSCPurfKSWEoaNHjqjYGCRtGVAXUJyuvIKyIlayssUlfMOgzdtMaOuTAZNDcHVUrLjxZZTCSicuFRn"
l175 = 372
lIIIllIIlIllllllllllIIlllllIlIlllIIIlIIlllIlIllIIIlIIIlllIlIlIIlIIIlllIIIllllllllIllIIIIlIlllIllIIIIlIllIlIlIIlIIlllIllIIlIllIlIlIlIlIIIllIlllIllIllIIIlIllIllllIlIIlIlIlIlllllII = 452
lIIIIIlllIlIllIIIlIIllIlllIIlIIlllIIIlIIIIllIlIIlIlIllIlIlllllIIIlIlIIIIIIIlIlllIIIllIIlIIlIlllIllIIlIllIllIIIlllIIlIlIlIllllIlIIllIllIIlIlIIIlIlIlIIIlllIIlIlIIlIlIllllllllllllIll = "ZqvYhWCyevGIANvzSMKRhksXdtGFPiFzkgmIsNivxZxGKPnIPYuSuiHSLKiwpKzuqVtIBuKGHGQwJTD"
llIlIIlIIIlllIIIIIIlIIIlIIIlIlIIlllIllllIIllIIIllllIIlIIllIIlIIIllIIlIlllIIlIIlIlIlIlIlIllIllIIIIIlIIlIllIlllIllllIlIIllIllIIIIlllllIllIIllIIlIlIIllIllIIllIlIlIIllllIlIIIlllIIIlIlII = "RQhBjtdzKZNcXOUhMACCvUxYlYFdDTclgItTpaTWNoOpvjZGWZlhLCYDGzziSHFCjFJlFeycmajCfjE"
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW = "ssdhwJzsUUlLauArXktQrmPwxJYGFQHkfACehNJqHsbcYdZgoNAyavOrIlVYfDipGEPVpLCcnwBTdKg"
r185 = "SYoTcyjCThxYFuSSyHTlRxDPTqFHxSSYOuMkRZFfAcuzJMYzRQvbOgxdxiDRDMAArImmkLcLxBAUEoi"
rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr = "LBjcJhoSHzLCONLmFjYoPLCLptuFkOuXCEPSjMURYCeBgwgnBLDWkWnwhpNXyrcCkvDsKIDAhYEwqNG"
QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ = "kjRQoYGYryDOJTKfEaKqbXcCRVIGgkMOqWoRSiJeFYVEWrqkqiaEtuigUSqOxtyDqhSHlNyLFXurrrk"
aaAAaAAaAaAaAaaaaAAaaaAaaaAAAAAaAaAAAaAAaAaaaaAAaAAAAaaaaAaAaAaAaaAAaaAAAAAAaaAaaaAaAAaaaaAAAaaaaaaAAaAaAAaAaAaaAAaAaaaAaAAAaaAaAaAaaAAAAAaaaAAAAaaaAaAaaAAAAAAaAaAAaaaAaaaAaAaaaAAaaaaaaaaAaAa = "ZRsLolFqmXPIYeSffWpLsckgsBIisGlKbftTSradZUVTXqehsXHKIxKKXyvyjAtupcgwggejpxvgpxM"
lllIIIIllllIlIlIlIIllllIlIIIlllIIIIIIllIlIIIIllIlIllIlIIllIIIlIlIIlIIlllIllIIllllIIllIllllllIIIllllllIlIIllIllllIllIIllIIIIIIIIIIlIlIllIlIIlIlIIlllIlIIIIIIlIIIIllIlIlIlIIlIIIIlIllIIIllllllIIIlI = 495
AAaAaAaaAaaaAAaAaaAAAaaaaaAAaAaaAaAAaaaaAAaAaaAaaaAaAAaAaaAaaAAaAaAAAaaaAaaaaaAaAAAAaaaaaaAaAAAAAaaaAAaaaaAaaAAaAAaAaaaAaaAaAAAaAaaAAAaAAAaAaAAaAaAaAaaaAAaaAaaAaAaAAAaaAAAaAaaAAaAaaAaaaAaaAaAaAaa = 389
jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj = "oDyeqQXRiKqdRYWFWmXdTYZqMHATAVWSdaQTjhKoXrnimGdsfXCKKyTeAhQBGNpcIPgmIIPObISgGKE"
sXBlpPtDfpvfYIZGHadlvVfoUNcQZjNVPvTEBiHUPTpMxVuAFoEZvUbGmRgPDzYOYYFNEmoYoEGxRrA199 = 296
S201 = "hxyhtuQFQncarAHARirOIVutQabwbukYuEoLRAVBYDFvkYQBoMFkQgEyKUWOVrgBqBXuFxhxWbNiFxz"
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm = 618
rakPgnaBAHAHlaACjsQtZzceuxeXWLeTjvlaoDLxOngoqjXEAMSkXIemKjrHPISUOBmGmhCzSziMXsr205 = 444
VKTdUpQUmOGIUyeLftZGQkAiMzloMlxyzkOpwDEoLlmcBpbTUDuQpQOmyMCjINjVsPDblsyBEoxuddE207 = "xyjFwQliqOqxIIMntfJtfMOKiGAUJDOamIdrxsDfTEhBNipPrczuIazoLxfywgWznogYxeVNXmvBaLm"
AaAaAaaaAAaaAaAAAaaAaAaaaAaaaaaaAaAaAaaAAaAaAAAaAAAaAaAAAaaaAAaAaaaAaaAaaaAAAAAaAAAaAaaaAAAaaAaaaAAAaaAAaAAAAAAAaaAAAAAAAaaAAAaaAaaaAAaaaAAaaaaaaAAAAaaAAAAAAAaAaAaAaAaAaaAAaAAaAaaAaAaAAaaaAAAaAAaAaAAAaaAAAAAAa = 305
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 497
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM = 513
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo = 389
AAAaaaaAAaaaaaAaAAaAaAAAaaaaAaAaAaAAAAAAaAaAaaaAAAAAaaaaaAaaaaAAAAAaAAAAAaAAaAAAAAAaAAAAAAAAAAAaAaAaAAAaaAAaAAAAaaAaAaaaAaAAAaaaaaAAAaaAAaAaAaaaaaaAaAaaAAaaAaaaaAaaAAAAAAAAAAaAaAAAAAaAaAaAaaAaaaaaaAaaAaaAAAAAAAAAAaAaa = 117
IllllIlllllIllIIllIlIlIIIllIIIlIIlIlllIIIllIIlIIIIIIIlIIIIllIllIIIIIIlIIlllllIllIlIlllIlIllIllllIlIIlIllIIlllllIlIlIIIlIIIIlIllIlIlIllIIIIIlIllllIlIllIIIIllIIIIlIllIlIIIlllIIIIllIlIIIlIIIIIIlIllllIllIlIIllllIIllIIIlIIIl = 268
j221 = 297

